export const dashboardColumns = [
  { header: "S.NO.", accessor: "sNo", className: "w-12 text-center sticky left-0 bg-white z-20" },
  { header: "IP", accessor: "ipName", className: "sticky left-12 bg-white z-20 min-w-[200px]" },
  { header: "District", accessor: "district", className: "sticky left-[212px] bg-white z-20 min-w-[150px]" },
  { header: "TARGET", accessor: "target", className: "text-center bg-blue-50/50 text-blue-900 font-bold sticky left-[362px] bg-white z-20" },
  { header: "Survey Done", accessor: "surveyDone", className: "text-center text-green-600" },
  { header: "Survey Pending", accessor: "surveyPending", className: "text-center text-orange-600 bg-orange-50/30" },
  { header: "Nos Of Complete Set Dispatch Plan", accessor: "dispatchPlanDone", className: "text-center" },
  { header: "Complete Set Dispatch DATE", accessor: "dispatchPlanDateCount", className: "text-center" },
  { header: "BALANCE DISPATCH PLAN", accessor: "balanceDispatchPlan", className: "text-center text-orange-600" },
  { header: "Material Dispatch ON Site", accessor: "materialDispatchDone", className: "text-center" },
  { header: "Material Dispatch ON Site Date", accessor: "materialDispatchDateCount", className: "text-center" },
  { header: "Installation Done", accessor: "installationDone", className: "text-center font-bold text-green-700 bg-green-50/30" },
  { header: "Installation Pending", accessor: "installationPending", className: "text-center text-red-600 font-medium" },
  { header: "PHOTO UPLODED MASTER SHEET", accessor: "photoUploadedMaster", className: "text-center" },
  { header: "PHOTO + RMS DATA PENDING", accessor: "photoRmsPending", className: "text-center text-orange-600" },
  { header: "UPAD ONLINE PORTAL SUPPLY", accessor: "upadSupplyDateCount", className: "text-center" },
  { header: "UP PORTAL PHOTO UPLODED", accessor: "upPortalPhotoUploaded", className: "text-center" },
  { header: "UP PORTAL PHOTO UPLODED PENDING", accessor: "upPortalPhotoPending", className: "text-center text-red-600" },
  { header: "INVOICE DONE", accessor: "invoiceDone", className: "text-center text-blue-700 font-medium" },
  { header: "Laxmi Invoice", accessor: "laxmiInvoiceDone", className: "text-center text-blue-700" },
  { header: "INVOICE PENDING", accessor: "invoicePending", className: "text-center text-orange-600" },
  { header: "JCR COMPLETED", accessor: "jcrCompleted", className: "text-center text-green-600" },
  { header: "JCR AT RBP (Pending)", accessor: "jcrPending", className: "text-center text-orange-600" },
  { header: "TOTAL JCR SUBMITTED", accessor: "totalJcrSubmitted", className: "text-center font-bold" },
  { header: "FARMER SHARE", accessor: "farmerShare", format: "currency", className: "text-right font-mono text-xs" },
  { header: "STATE SHARE", accessor: "stateShare", format: "currency", className: "text-right font-mono text-xs" },
  { header: "INSURANCE UPLODED MASTER SHEET", accessor: "insuranceUploaded", className: "text-center" },
  { header: "SCADA PORTAL LOT CREATION DONE", accessor: "scadaLotDone", className: "text-center" },
  { header: "RMS INTEGRATION MAPPING DONE MAIL TO ROTOMAG", accessor: "rmsMappingDone", className: "text-center" },
  { header: "7 DAYS RMS INTEGRATION VERIFICATION VALID", accessor: "sevenDaysVerification", className: "text-center" },
];
